"""Add date column to machine_calibration

Revision ID: 0e19edc0d1d8
Revises: 4ed63c9edf7b
Create Date: 2025-04-23 14:37:30.506818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e19edc0d1d8'
down_revision = '4ed63c9edf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_calibration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_calibration', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
