"""Add MaintenanceReport model

Revision ID: 4ed63c9edf7b
Revises: 
Create Date: 2025-04-22 16:08:27.126055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed63c9edf7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('model_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('station', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('affected_component', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('problem_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('evidence', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('analysis', sa.Text(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('location_line')
        batch_op.drop_column('priority')
        batch_op.drop_column('resolved_date')
        batch_op.drop_column('description')
        batch_op.drop_column('resolution')
        batch_op.drop_column('report_type')
        batch_op.drop_column('reported_date')
        batch_op.drop_column('machine_name')
        batch_op.drop_column('reported_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('machine_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('reported_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('report_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('resolution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('resolved_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('location_line', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('analysis')
        batch_op.drop_column('evidence')
        batch_op.drop_column('problem_description')
        batch_op.drop_column('quantity')
        batch_op.drop_column('affected_component')
        batch_op.drop_column('station')
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_id')
        batch_op.drop_column('model_name')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
