"""Remove remaining, missing, remarks from ITInventory

Revision ID: 5fa4da55e59d
Revises: 9070598a123b
Create Date: 2025-04-24 15:24:59.897526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa4da55e59d'
down_revision = '9070598a123b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.drop_column('missing')
        batch_op.drop_column('remaining')
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('remaining', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('missing', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
