"""Add brand and numbers_of_ng to ITInventory

Revision ID: 8d084c721594
Revises: 5fa4da55e59d
Create Date: 2025-05-14 14:38:49.016823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d084c721594'
down_revision = '5fa4da55e59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numbers_of_ng', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.drop_column('numbers_of_ng')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
