"""Create ITInventory table

Revision ID: 9070598a123b
Revises: 0e19edc0d1d8
Create Date: 2025-04-24 15:18:41.802681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9070598a123b'
down_revision = '0e19edc0d1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('acquired_qty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('remaining', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('missing', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('warranty_expiration')
        batch_op.drop_column('equipment_type')
        batch_op.drop_column('notes')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('status')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('asset_tag')
        batch_op.drop_column('created_at')
        batch_op.drop_column('location')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('it_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('asset_tag', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('equipment_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('warranty_expiration', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('remarks')
        batch_op.drop_column('missing')
        batch_op.drop_column('remaining')
        batch_op.drop_column('acquired_qty')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('item_name')

    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('machine_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('calibration_date', sa.DATETIME(), nullable=False),
    sa.Column('days_remaining', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
